spring:
  application:
    name: orders-service

  datasource:
    url: jdbc:postgresql://localhost:5433/ordersdb
    username: mengzhou
    password: password123
    driver-class-name: org.postgresql.Driver

  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

server:
  port: 8081
